export enum ActionType {
    ADD_EMPLOYEE = "ADD_EMPLOYEE",
    EDIT_EMPLOYEE = "EDIT_EMPLOYEE",
    REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE",
    FETCH_EMPLOYEES = "FETCH_EMPLOYEES",
    TOGGLE_GRID = "TOGGLE_GRID",
    FETCH_EMPLOYEES_ERROR = "FETCH_EMPLOYEES_ERROR",
    EDIT_EMPLOYEE_ERROR = "EDIT_EMPLOYEE_ERROR",
    REMOVE_EMPLOYEE_ERROR = "REMOVE_EMPLOYEE_ERROR",
    ADD_EMPLOYEES_ERROR = "ADD_EMPLOYEES_ERROR",
    ERRORS_RESET = "ERRORS_RESET",
}